### PR TITLE
Convert to typescript, compile with tsc command line, use project-local tslint and eslint config files.

### PR DESCRIPTION
**Pull request by rictic**

### CODE REVIEW

**Comment by FredKSchott** [comment]
Isn't there a 🐔 🥚  problem here? If the gulp file runs our build process, and the gulpfile itself needs to be built before running, how does someone run their first build?

**Comment by rictic** [comment]
Oh, right, ha!

Lemmy see if there's an elegant fix…

**Comment by rictic** [comment]
The package.json file for this package (rather than the package.template.json file) is overcomplicated anyways. I simplified it down, and eliminated the chicken and egg problem.

PTAL.

**Comment by aomarks** [comment]
Closing this pull request because this repo is now archived. If this PR is still active, please submit a new one at https://github.com/Polymer/tools.

**Pull request closed without merging**
